# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'team_with_calender.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from datetime import datetime
import sys
from PyQt5.QtWidgets import *
from PyQt5 import uic
from PyQt5.QtCore import *
import pandas as pd
import matplotlib.pyplot as plt
from PyQt5.QtGui import *
from PyQt5 import QtCore, QtGui, QtWidgets


from PyQt5.QtGui import QStandardItem, QStandardItemModel
from PyQt5.QtWidgets import QAbstractItemView, QApplication, QTableView
bitcoin = pd.read_csv("BTC-USD.csv",index_col="Date")

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 602)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 371, 531))
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 20, 351, 251))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(140, 20, 22, 16))
        self.label_2.setObjectName("label_2")
        self.labelCoinName = QtWidgets.QLabel(self.groupBox_3)
        self.labelCoinName.setGeometry(QtCore.QRect(10, 20, 22, 16))
        self.labelCoinName.setObjectName("labelCoinName")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit.setGeometry(QtCore.QRect(190, 10, 133, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox.setGeometry(QtCore.QRect(60, 20, 69, 20))
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox.setObjectName("comboBox")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.groupBox_3)
        self.calendarWidget.setGeometry(QtCore.QRect(10, 50, 331, 191))
        self.calendarWidget.setObjectName("calendarWidget")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 300, 251, 221))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButtonApply = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonApply.setGeometry(QtCore.QRect(550, 320, 75, 23))
        self.pushButtonApply.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonApply.setObjectName("pushButtonApply")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(640, 30, 151, 281))
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.splitter = QtWidgets.QSplitter(self.groupBox_2)
        self.splitter.setGeometry(QtCore.QRect(11, 35, 131, 241))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.pushButton = QtWidgets.QPushButton(self.splitter)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_4 = QtWidgets.QPushButton(self.splitter)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.splitter)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.splitter)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.splitter)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setObjectName("pushButton_5")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(390, 30, 241, 281))
        self.groupBox_5.setObjectName("groupBox_5")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 90, 221, 171))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_7.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_7)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_5.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_6)
        self.pushButtonCancel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCancel.setGeometry(QtCore.QRect(640, 320, 75, 23))
        self.pushButtonCancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.pushButtonSave = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSave.setGeometry(QtCore.QRect(460, 320, 75, 23))
        self.pushButtonSave.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(540, 460, 171, 34))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 239, 163))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 239, 163))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 239, 163))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 239, 163))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 239, 163))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 239, 163))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 239, 163))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 239, 163))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 239, 163))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_7.setPalette(palette)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 239, 163))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 239, 163))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 239, 163))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 239, 163))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 239, 163))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 239, 163))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 239, 163))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 239, 163))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 239, 163))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_8.setPalette(palette)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Input"))
        self.groupBox_3.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_2.setText(_translate("MainWindow", "날짜"))
        self.labelCoinName.setText(_translate("MainWindow", "종목"))
        self.groupBox_4.setTitle(_translate("MainWindow", "GroupBox"))
        self.pushButtonApply.setText(_translate("MainWindow", "Apply"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Graph"))
        self.pushButton.setText(_translate("MainWindow", "시가 그래프"))
        self.pushButton_4.setText(_translate("MainWindow", "종가 그래프"))
        self.pushButton_2.setText(_translate("MainWindow", "고가 그래프"))
        self.pushButton_3.setText(_translate("MainWindow", "저가 그래프"))
        self.pushButton_5.setText(_translate("MainWindow", "이동 평균선 그래프"))
        self.groupBox_5.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_11.setText(_translate("MainWindow", "현재가격"))
        self.label_3.setText(_translate("MainWindow", "시가"))
        self.label_4.setText(_translate("MainWindow", "고가"))
        self.label_5.setText(_translate("MainWindow", "저가"))
        self.label_6.setText(_translate("MainWindow", "종가"))
        self.label_10.setText(_translate("MainWindow", "알림기준"))
        self.pushButtonCancel.setText(_translate("MainWindow", "Cancel"))
        self.pushButtonSave.setText(_translate("MainWindow", "Save"))
        self.label_7.setText(_translate("MainWindow", "*YYYY-MM-DD 형식으로 입력한 뒤,"))
        self.label_8.setText(_translate("MainWindow", "[ENTER]를 눌러주세요."))


class MyWindow(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.setWindowTitle("BITCOIN")
        self.setWindowIcon(QIcon("bitbit.png"))

        self.pushButton.clicked.connect(self.btn_clicked)
        self.pushButton_2.clicked.connect(self.btn_clicked_2)
        self.pushButton_3.clicked.connect(self.btn_clicked_3)
        self.pushButton_4.clicked.connect(self.btn_clicked_4)
        self.pushButton_5.clicked.connect(self.btn_clicked_5)
        self.pushButtonCancel.clicked.connect(self.close)
        self.pushButtonSave.clicked.connect(self.save)
        self.lineEdit.returnPressed.connect(self.inquiry)

        ###
        self.calendarWidget = self.findChild(QCalendarWidget, "calendarWidget")
        self.lineEdit = self.findChild(QLineEdit, "lineEdit")
        self.calendarWidget.selectionChanged.connect(self.calendar_date)
        ###

    ###
    def  calendar_date(self):
        dateSelected = self.calendarWidget.selectedDate()
        date_in_string = str(dateSelected.toPyDate())

        self.lineEdit.setText(date_in_string)
    ###


    def btn_clicked(self):
        plt.plot(bitcoin["Open"])
        plt.legend(loc="best")
        plt.grid()
        plt.show()

    def btn_clicked_2(self):
        plt.plot(bitcoin["High"])
        plt.legend(loc="best")
        plt.grid()
        plt.show()

    def btn_clicked_3(self):
        plt.plot(bitcoin["Low"])
        plt.legend(loc="best")
        plt.grid()
        plt.show()

    def btn_clicked_4(self):
        plt.plot(bitcoin["Close"])
        plt.legend(loc="best")
        plt.grid()
        plt.show()

    def btn_clicked_5(self):
        ma5 = bitcoin['Adj Close'].rolling(window=5).mean()
        ma20 = bitcoin['Adj Close'].rolling(window=20).mean()
        ma60 = bitcoin['Adj Close'].rolling(window=60).mean()
        ma120 = bitcoin['Adj Close'].rolling(window=120).mean()
        bitcoin.insert(len(bitcoin.columns), "MA5", ma5)
        bitcoin.insert(len(bitcoin.columns), "MA20", ma20)
        bitcoin.insert(len(bitcoin.columns), "MA60", ma60)
        bitcoin.insert(len(bitcoin.columns), "MA120", ma120)
        plt.plot(bitcoin.index, bitcoin['Adj Close'], label='Adj Close')
        plt.plot(bitcoin.index, bitcoin['MA5'], label='MA5')
        plt.plot(bitcoin.index, bitcoin['MA20'], label='MA20')
        plt.plot(bitcoin.index, bitcoin['MA60'], label='MA60')
        plt.plot(bitcoin.index, bitcoin['MA120'], label='MA120')
        plt.legend(loc="best")
        plt.grid()
        plt.show()

    def refine_date(self, date):
        a = list()
        refined_date = ""
        for i in range(3):
            apd = date.split("-")[i]
            a.append(apd)
        a[2] = a[2][0] + a[2][1]
        for i in range(3):
            refined_date += a[i]
            if i != 2:
                refined_date += "-"
        return refined_date

    def inquiry(self):
        date = self.lineEdit.text()
        refined_date = self.refine_date(date)
        print(refined_date)
        day_data = bitcoin.loc[refined_date, "Open"]
        self.lineEdit_2.setText(str(day_data))
        day_data2 = bitcoin.loc[refined_date, "High"]
        self.lineEdit_3.setText(str(day_data2))
        day_data3 = bitcoin.loc[refined_date, "Low"]
        self.lineEdit_4.setText(str(day_data3))
        day_data4 = bitcoin.loc[refined_date, "Close"]
        self.lineEdit_5.setText(str(day_data4))

    ###
    def save(self):
        with open('BTC_save.txt','w') as f:
            date = self.lineEdit.text()
            refined_date = self.refine_date(date)
            if str(refined_date) == "":
                self.WarningWindow.setText("날짜를 먼저 입력해주세요")
            else:
                f.write("The Date of Result : ")
                f.write(str(refined_date))
                f.write("\n")
                day_data = bitcoin.loc[refined_date, "Open"]
                f.write("Open : ")
                f.write(str(day_data))
                f.write("\n")
                day_data2 = bitcoin.loc[refined_date, "High"]
                f.write("High : ")
                f.write(str(day_data2))
                f.write("\n")
                day_data3 = bitcoin.loc[refined_date, "Low"]
                f.write("Low : ")
                f.write(str(day_data3))
                f.write("\n")
                day_data4 = bitcoin.loc[refined_date, "Close"]
                f.write("Close : ")
                f.write(str(day_data4))
                f.write("\n")
                f.write("Date the file was saved : ")
                f.write(str(datetime.now()))
    ###


app = QApplication(sys.argv)
window = MyWindow()
window.show()
app.exec_()